name: Pip

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest] # windows-latest excluded for now
        python-version: ["3.7", "3.11"]
        exclude:
          # 3.7 is not available anymore on macos-latest
          - platform: macos-latest
            python-version: "3.7"

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
        fetch-depth: 0

    - name: Write version.txt on release event
      if: github.event_name == 'release'
      run: echo ${{ github.event.release.tag_name }} > VERSION.txt

    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Add requirements
      run: python -m pip install --upgrade wheel setuptools

    - name: Build and install
      run: pip install --verbose .[test]

    - name: Test
      run: python -m pytest test.py
