name: Wheels

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
     - main
  release:
    types:
      - published

jobs:
  build_sdist:
    name: Build SDist
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 0

    - name: Install OpenSSL Development Libraries (Ubuntu)
      if: runner.os == 'Linux'
      run: sudo apt-get update && sudo apt-get install -y libssl-dev

    - name: Install OpenSSL Development Libraries (macOS)
      if: runner.os == 'macOS'
      run: brew install openssl

    - name: Write version.txt on release event
      if: github.event_name == 'release'
      run: echo ${{ github.event.release.tag_name }} > VERSION.txt

    - name: Build SDist
      run: pipx run build --sdist

    - name: Check metadata
      run: pipx run twine check dist/*

    - uses: actions/upload-artifact@v4
      with:
        name: source-archive-${{ github.job }}
        path: dist/*.tar.gz


  build_wheels:
    name: Wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest] # windows-latest, excluded for now

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 0

    - name: Install OpenSSL development libraries
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get update && sudo apt-get install -y libssl-dev

    - name: Install OpenSSL for macOS
      if: matrix.os == 'macos-latest'
      run: brew install openssl
    
    - name: Set up QEMU
      if: runner.os == 'Linux'
      uses: docker/setup-qemu-action@v3
      with:
        platforms: all
    
    - name: Write version.txt on release event
      if: github.event_name == 'release'
      run: echo ${{ github.event.release.tag_name }} > VERSION.txt

    - uses: pypa/cibuildwheel@v2.17.0
      env:
        CIBW_ARCHS_MACOS: auto universal2
        CIBW_ARCHS_LINUX: auto aarch64
        CIBW_MANYLINUX_X86_64_IMAGE: quay.io/pypa/manylinux_2_28_x86_64
        CIBW_MANYLINUX_AARCH64_IMAGE: quay.io/pypa/manylinux_2_28_aarch64
        CIBW_MUSLLINUX_X86_64_IMAGE: quay.io/pypa/musllinux_1_2_x86_64
        CIBW_MUSLLINUX_AARCH64_IMAGE: quay.io/pypa/musllinux_1_2_aarch64
        CIBW_BEFORE_ALL_LINUX: if command -v apk > /dev/null; then apk add --no-cache libatomic; else dnf install -y libatomic; fi
        CIBW_SKIP: pp* cp36-* cp37-* *-manylinux_i686
        MACOSX_DEPLOYMENT_TARGET: 10.15

    - name: Verify clean directory
      run: git diff --exit-code
      shell: bash

    - name: Upload wheels
      uses: actions/upload-artifact@v4
      with:
        name: wheelhouse-${{ matrix.os }}
        path: wheelhouse/*.whl


  upload_all:
    name: Upload if release
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'

    steps:
    - uses: actions/setup-python@v5
      with:
        python-version: "3.x"

    - uses: actions/download-artifact@v4
      with:
        path: dist
        merge-multiple: true

    - uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_TOKEN }}
